### ISSUE TITLE
[FEATURE]: Add option on the check method for manage the "at least one" tag from array is present

### ISSUE THREAD

**Issue by p4535992** [ZotyDev/FoundryVTT-ItemTags#8]
### Discord Username

4535992

### Enhancement Type

Feature

### Request

We use your module for simple checks with the method

`ItemTags.Check(item, ['tag1','tag2'])`

but we would need to have the option that check the case of "at least one of the tags is present", something like:

```
const atLeastOneTagIsPresent = true;
ItemTags.Check(item, ['tag1','tag2'], atLeastOneTagIsPresent)
```

I could code with the advanced method and Search All, but I have to have it used by person co 0 code knowledge and this would be the ideal solution for my use case.

**Comment by ZotyDev** [comment]
For sure! I will add it asap and notify you!

**Comment by ZotyDev** [comment]
Well... Turns out this was already implemented, just not described on the documentation...
Anyway, I've updated the [docs](https://modules.zoty.dev/itemTags/apiReference.html#check-tags) and exposed a method that should have been exposed from the start ([`CheckString()`](https://modules.zoty.dev/itemTags/apiReference.html#check-tags-by-string)).
